connect SYSTEM/Oracle2021@localhost:1521/DB1
connect NATAME/NATAME@localhost:1521/DB1
connect ADMINNATAME/ADMINNATAME@localhost:1521/DB1
connect CLIENTE_PRUEBA/PRUEBA@localhost:1521/DB1

CREATE USER CLIENTE_PRUEBA IDENTIFIED BY PRUEBA 
DEFAULT TABLESPACE NATAME 
TEMPORARY TABLESPACE NATAME_TMP 
QUOTA 4M ON NATAME 
PASSWORD EXPIRE;

GRANT CONSULTOR TO CLIENTE_PRUEBA; 

CREATE USER REP_VENTA1 IDENTIFIED BY rep123
DEFAULT TABLESPACE NATAME 
TEMPORARY TABLESPACE NATAME_TMP 
QUOTA 4M ON NATAME
PASSWORD EXPIRE;

GRANT gestor_c1 TO REP_VENTA1;

CREATE USER REP_VENTA2 IDENTIFIED BY rep123
DEFAULT TABLESPACE PROY_DEF 
TEMPORARY TABLESPACE PROY_TEMP 
QUOTA 4M ON PROY_DEF 
PASSWORD EXPIRE;

GRANT gestor_c2 TO REP_VENTA2;

GRANT supervisor TO admproy;

CREATE PLUGGABLE DATABASE PROYPDB
  ADMIN USER SYSTEMPDB IDENTIFIED BY Oracle2021
  STORAGE (MAXSIZE 2G)
  DEFAULT TABLESPACE PROY
    DATAFILE 'C:\app\braya\product\18.0.0\oradata\XE\BASESPROY\PROYPDB.dbf' SIZE 4M 
    AUTOEXTEND ON
    PATH_PREFIX = 'C:\app\braya\product\18.0.0\oradata\XE\BASESPROY\'
    FILE_NAME_CONVERT = ('C:\app\braya\product\18.0.0\oradata\XE\pdbseed\', 
                         'C:\app\braya\product\18.0.0\oradata\XE\BASESPROY\');
