CREATE USER CLIENTE_CEDULA IDENTIFIED BY CEDULA 
DEFAULT TABLESPACE PROY_DEF 
TEMPORARY TABLESPACE PROY_TEMP 
QUOTA 4M ON PROY_DEF 
PASSWORD EXPIRE;

GRANT consultor TO CLIENTE_CEDULA; 

CREATE USER REP_VENTA1 IDENTIFIED BY rep123
DEFAULT TABLESPACE PROY_DEF 
TEMPORARY TABLESPACE PROY_TEMP 
QUOTA 4M ON PROY_DEF 
PASSWORD EXPIRE;

GRANT gestor_c1 TO REP_VENTA1;

CREATE USER REP_VENTA2 IDENTIFIED BY rep123
DEFAULT TABLESPACE PROY_DEF 
TEMPORARY TABLESPACE PROY_TEMP 
QUOTA 4M ON PROY_DEF 
PASSWORD EXPIRE;

GRANT gestor_c2 TO REP_VENTA2;

GRANT supervisor TO admproy;
