-- Insertar Regiones
INSERT INTO "Region" (FK_ID_DIRECTOR, NOMBRE) VALUES (NULL, 'Caribe');
INSERT INTO "Region" (FK_ID_DIRECTOR, NOMBRE) VALUES (NULL, 'Amazonia');
INSERT INTO "Region" (FK_ID_DIRECTOR, NOMBRE) VALUES (NULL, 'Andina');
INSERT INTO "Region" (FK_ID_DIRECTOR, NOMBRE) VALUES (NULL, 'Insular');
INSERT INTO "Region" (FK_ID_DIRECTOR, NOMBRE) VALUES (NULL, 'Orinoquia');
INSERT INTO "Region" (FK_ID_DIRECTOR, NOMBRE) VALUES (NULL, 'Pacifica');

-- Insertar Representantes
INSERT into "Representante" (CEDULA, FK_ID_REGION, FK_ID_REP_PADRE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO_ELECTRONICO, GENERO, FECHA_NACIMIENTO, FECHA_CONTRATO, TEL_CONTACTO, GRADO, ESTADO, CIUDAD, DIRECCION)
                    VALUES (1193220649, 1, NULL, 'Arley', 'Esteban', 'Quintero', 'Amaya', 'prueba@gmail.com', 'M', '30-08-2000', '22-08-2021', 3006485671, 'master', 'A', 'Santa Marta', 'Calle 1');

INSERT into "Representante" (CEDULA, FK_ID_REGION, FK_ID_REP_PADRE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO_ELECTRONICO, GENERO, FECHA_NACIMIENTO, FECHA_CONTRATO, TEL_CONTACTO, GRADO, ESTADO, CIUDAD, DIRECCION)
                    VALUES (1234567890, 3, 1193220649, 'Mateo', NULL, 'Yate', 'Gonzalez', 'prueba2@gmail.com', 'M', '01-02-1999', '22-08-2021', 3006485672, 'beginner', 'A', 'Bogotá', 'Calle 2');

INSERT into "Representante" (CEDULA, FK_ID_REGION, FK_ID_REP_PADRE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO_ELECTRONICO, GENERO, FECHA_NACIMIENTO, FECHA_CONTRATO, TEL_CONTACTO, GRADO, ESTADO, CIUDAD, DIRECCION)
                    VALUES (2345678901, 3, 1193220649, 'Kevin', 'Andres', 'Borda', 'Penagos', 'prueba3@gmail.com', 'M', '03-04-2000', '22-08-2021', 3006485673, 'beginner', 'A', 'Bogotá', 'Calle 3');

INSERT into "Representante" (CEDULA, FK_ID_REGION, FK_ID_REP_PADRE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO_ELECTRONICO, GENERO, FECHA_NACIMIENTO, FECHA_CONTRATO, TEL_CONTACTO, GRADO, ESTADO, CIUDAD, DIRECCION)
                    VALUES (3456789012, 2, NULL, 'Brayan', 'Alexander', 'Paredes', 'Sanchez', 'prueba4@gmail.com', 'M', '20-09-1999', '22-08-2021', 3006485674, 'senior', 'A', 'Leticia', 'Calle 4');

INSERT into "Representante" (CEDULA, FK_ID_REGION, FK_ID_REP_PADRE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO_ELECTRONICO, GENERO, FECHA_NACIMIENTO, FECHA_CONTRATO, TEL_CONTACTO, GRADO, ESTADO, CIUDAD, DIRECCION)
                    VALUES (4567890123, 4, NULL, 'Diego', 'Alejandro', 'Gonzalez', NULL, 'prueba5@gmail.com', 'M', '20-09-1999', '22-08-2021', 3006485675, 'junior', 'A', 'San Andrés', 'Calle 5');

-- Insertar Clientes

INSERT into "Cliente" (CEDULA, FK_CEDULA_REPRESENTANTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO_ELECTRONICO, GENERO, FECHA_NACIMIENTO, TEL_CONTACTO, ESTADO, CIUDAD, DIRECCION)
            VALUES (9283748392, 1193220649, 'Alba', 'Consuelo', 'Nieto', 'Lemus', 'prueba7@gmail.com', 'F', '03-03-1968', 3009456852, 'A', 'Bogotá', 'Calle 7');

INSERT into "Cliente" (CEDULA, FK_CEDULA_REPRESENTANTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO_ELECTRONICO, GENERO, FECHA_NACIMIENTO, TEL_CONTACTO, ESTADO, CIUDAD, DIRECCION)
            VALUES (9283748391, 1193220649, 'Andres', 'Manuel', 'Lopez', 'Obrador', 'prueba6@gmail.com', 'M', '03-03-2003', 3009456851, 'A', 'Bogotá', 'Calle 6');

-- Insertar Periodos
INSERT INTO "Periodo" (ID_PERIODO, FECHA_INICIO, FECHA_FIN) VALUES (1, '01-01-2021', '31-01-2021');
INSERT INTO "Periodo" (ID_PERIODO, FECHA_INICIO, FECHA_FIN) VALUES (2, '01-02-2021', '28-02-2021');

-- Insertar en RepresentantePeriodo
INSERT INTO "RepresentantePeriodo" (FK_CEDULA_REPRESENTANTE, FK_ID_PERIODO, MONTO, GRADO, PORCENTAJE)
                        VALUES (1193220649, 1, 2000000, 'master', 8);

INSERT INTO "RepresentantePeriodo" (FK_CEDULA_REPRESENTANTE, FK_ID_PERIODO, MONTO, GRADO, PORCENTAJE)
                        VALUES (1193220649, 2, 3000000, 'master', 8);