/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 23-ago.-2021 4:39:06 p. m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Triggers, Sequences for Autonumber Columns */

DROP TRIGGER "TRG_Categoria_ID_CATEGORIA";
DROP SEQUENCE "SEQ_Categoria_ID_CATEGORIA";

DROP TRIGGER "TRG_Pedido_ID_PEDIDO";
DROP SEQUENCE "SEQ_Pedido_ID_PEDIDO";

DROP TRIGGER "TRG_Region_ID_REGION";
DROP SEQUENCE "SEQ_Region_ID_REGION";

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TRIGGERS 
  WHERE TRIGGER_NAME = 'TRG_Categoria_ID_CATEGORIA'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER "TRG_Categoria_ID_CATEGORIA"'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_SEQUENCES 
  WHERE SEQUENCE_NAME = 'SEQ_Categoria_ID_CATEGORIA'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE "SEQ_Categoria_ID_CATEGORIA"'; 
END IF; 
END;
/


DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TRIGGERS 
  WHERE TRIGGER_NAME = 'TRG_Pedido_ID_PEDIDO'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER "TRG_Pedido_ID_PEDIDO"'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_SEQUENCES 
  WHERE SEQUENCE_NAME = 'SEQ_Pedido_ID_PEDIDO'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE "SEQ_Pedido_ID_PEDIDO"'; 
END IF; 
END;
/


DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TRIGGERS 
  WHERE TRIGGER_NAME = 'TRG_Region_ID_REGION'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER "TRG_Region_ID_REGION"'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_SEQUENCES 
  WHERE SEQUENCE_NAME = 'SEQ_Region_ID_REGION'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE "SEQ_Region_ID_REGION"'; 
END IF; 
END;
/


/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Categoria" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Cliente" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Inventario" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Pedido" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PedidoProducto" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Periodo" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Producto" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Region" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Representante" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "RepresentantePeriodo" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

/* Create Tables */

CREATE TABLE  "Categoria"
(
	"ID_CATEGORIA" NUMBER(4) NOT NULL,	-- Identificador de la categoría
	"FK_CATEGORIA_PADRE" NUMBER(4) NULL,	-- Identificador de la categoría padre
	"NOMBRE" VARCHAR(15) NOT NULL	-- Nombre de la categoría (Ej: Hogar)
)
;

CREATE TABLE  "Cliente"
(
	"CEDULA" NUMBER(10) NOT NULL,	-- Documento de Identidad del Cliente
	"FK_CEDULA_REPRESENTANTE" NUMBER(10) NOT NULL,	-- Documento de Identidad de su representante actual
	"PRIMER_NOMBRE" VARCHAR(20) NOT NULL,	-- Primer Nombre del cliente
	"SEGUNDO_NOMBRE" VARCHAR(20) NULL,	-- Segundo nombre del cliente
	"PRIMER_APELLIDO" VARCHAR(20) NOT NULL,	-- Primer apellido del cliente
	"SEGUNDO_APELLIDO" VARCHAR(20) NULL,	-- Segundo apellido del cliente
	"CORREO_ELECTRONICO" VARCHAR(30) NOT NULL,	-- Correo electrónico del cliente
	"GENERO" VARCHAR(9) NOT NULL,	-- Genero del cliente (Masculino o Femenino)
	"FECHA_NACIMIENTO" DATE NOT NULL,	-- Fecha de nacimiento del cliente
	"TEL_CONTACTO" NUMBER(10) NOT NULL,	-- Teléfono de contacto del cliente
	"ESTADO" CHAR(1) DEFAULT 'A' NOT NULL,	-- Estado de actividad del cliente dentro del sistema (A: Activo, I: Inactivo)
	"CIUDAD" VARCHAR(25) NOT NULL,
	"DIRECCION" VARCHAR(60) NOT NULL
)
;

CREATE TABLE  "Inventario"
(
	"FK_ID_REGION" NUMBER(4) NOT NULL,	-- Identificador de la región a la cual pertenece el producto
	"FK_ID_PRODUCTO" NUMBER(8) NOT NULL,	-- Identificador del producto perteneciente a la región
	"PRECIO" NUMBER(6) NOT NULL	-- Precio del producto
)
;

CREATE TABLE  "Pedido"
(
	"ID_PEDIDO" NUMBER(8) NOT NULL,	-- Identificador del pedido
	"FK_CEDULA_REPRESENTANTE" NUMBER(10) NOT NULL,	-- Documento de identidad del representante que realizó el pedido
	"FK_CEDULA_CLIENTE" NUMBER(10) NOT NULL,	-- Documento de identidad del cliente que ordenó el pedido
	"MONTO" NUMBER(11) NOT NULL,	-- Precio total del pedido (Calculado por la Base de Datos)
	"CALIFICACION_REP" NUMBER(1) NOT NULL,	-- Calificación de 0 a 5 proporcionada por el cliente dependiendo de la calidad del servicio ootorgada por el representante
	"TIPO_PAGO" CHAR(1) DEFAULT 'N' NOT NULL,	-- Tipo de pago seleccionado por el cliente (P: PSE, C: Tarjeta de crédito)
	"ESTADO" CHAR(2) DEFAULT 'PP' NOT NULL,	-- Estado del pago del pedido (PP: Por Pagar (Por defecto), C: Cancelado)
	"FECHA_PEDIDO" DATE NOT NULL	-- Fecha donde el pedido fue cancelado por el cliente
)
;

CREATE TABLE  "PedidoProducto"
(
	"FK_ID_PEDIDO" NUMBER(8) NOT NULL,	-- Identificador del pedido realizado por el representante y ordenado por el cliente
	"FK_ID_PRODUCTO" NUMBER(8) NOT NULL	-- Identificador de un producto que haya sido ordenado en el pedido
)
;

CREATE TABLE  "Periodo"
(
	"ID_PERIODO" NUMBER(8) NOT NULL,	-- Identificador del periodo de campaña
	"FECHA_INICIO" DATE NOT NULL,	-- Fecha inicial del periodo
	"FECHA_FIN" DATE NOT NULL	-- Fecha final del pedido
)
;

CREATE TABLE  "Producto"
(
	"ID_PRODUCTO" NUMBER(8) NOT NULL,	-- Identificador del producto
	"FK_ID_CATEGORIA" NUMBER(4) NOT NULL,	-- Identificador de la categoría a la que pertenece el producto
	"NOMBRE" VARCHAR(30) NOT NULL	-- Nombre del producto
)
;

CREATE TABLE  "Region"
(
	"ID_REGION" NUMBER(4) NOT NULL,	-- Identificador de la región
	"FK_ID_DIRECTOR" NUMBER(10) NULL,	-- Identificador del representante que ocupa el puesto de director en la región
	"NOMBRE" VARCHAR(20) NOT NULL	-- Nombre de la región
)
;

CREATE TABLE  "Representante"
(
	"CEDULA" NUMBER(10) NOT NULL,	-- Documento de identidad del representante
	"FK_ID_REGION" NUMBER(4) NOT NULL,	-- Identificador de la región a la cual está afiliada el representante
	"FK_ID_REP_PADRE" NUMBER(10) NULL,	-- Identificador del representante que lo afilió al sistema
	"PRIMER_NOMBRE" VARCHAR(20) NOT NULL,	-- Primer nombre del representante
	"SEGUNDO_NOMBRE" VARCHAR(20) NULL,	-- Segundo nombre del representante
	"PRIMER_APELLIDO" VARCHAR(20) NOT NULL,	-- Primer apellido del representante
	"SEGUNDO_APELLIDO" VARCHAR(20) NULL,	-- Segundo apellido del representante
	"CORREO_ELECTRONICO" VARCHAR(30) NOT NULL,	-- Correo electrónico del representante
	"GENERO" VARCHAR(9) NOT NULL,	-- Género del representante (Masculino o Femenino)
	"FECHA_NACIMIENTO" DATE NOT NULL,	-- Fecha de nacimiento del representante
	"FECHA_CONTRATO" DATE NOT NULL,	-- Fecha en la que el usuario adquirió los privilegios de representante
	"TEL_CONTACTO" NUMBER(10) NOT NULL,	-- Teléfono de contacto del representante
	"GRADO" VARCHAR(8) DEFAULT 'beginner' NOT NULL,	-- Grado actual del representante (beginner (Por defecto), junior, senior, master) asignado en el último periodo
	"PROM_CALIFICACION" NUMBER(2,1) NULL,	-- Promedio de calificaciones asignadas por sus clientes en cada uno de sus pedidos
	"TOTAL_VENTA" NUMBER(11) DEFAULT 0 NOT NULL,	-- Monto total de ventas del representante (Calculado por la Base de Datos)
	"ESTADO" CHAR(1) DEFAULT 'A' NOT NULL,	-- Estado de actividad del representante (A: Activo (Por defecto), I: Inactivo)
	"CIUDAD" VARCHAR(25) NOT NULL,
	"DIRECCION" VARCHAR(60) NOT NULL
)
;

CREATE TABLE  "RepresentantePeriodo"
(
	"FK_CEDULA_REPRESENTANTE" NUMBER(10) NOT NULL,	-- Documento de identidad del representante
	"FK_ID_PERIODO" NUMBER(8) NOT NULL,	-- Identificador del periodo a calificar
	"MONTO" NUMBER(11) NOT NULL,	-- Venta total del representante en el periodo correspondiente
	"GRADO" VARCHAR(8) NOT NULL,	-- Grado del representante (beginner, junior, senior, master) del periodo correspondiente (Calculado en la aplicación)
	"PORCENTAJE" NUMBER(2) NOT NULL	-- Porcentaje de comision del representante correspondiente a su grado actual
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  "Categoria" IS 'Tabla que almacena los datos de las Categorias'
;


COMMENT ON COLUMN  "Categoria"."ID_CATEGORIA" IS 'Identificador de la categoría';

COMMENT ON COLUMN  "Categoria"."FK_CATEGORIA_PADRE" IS 'Identificador de la categoría padre';

COMMENT ON COLUMN  "Categoria"."NOMBRE" IS 'Nombre de la categoría (Ej: Hogar)';

CREATE SEQUENCE "SEQ_Categoria_ID_CATEGORIA" 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;


CREATE OR REPLACE TRIGGER "TRG_Categoria_ID_CATEGORIA" 
	BEFORE INSERT 
	ON "Categoria" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_Categoria_ID_CATEGORIA".NEXTVAL 
		INTO :NEW."ID_CATEGORIA" 
		FROM DUAL; 
	END;

/


COMMENT ON TABLE  "Cliente" IS 'Tabla que almacena los datos de los Clientes'
;


COMMENT ON COLUMN  "Cliente"."CEDULA" IS 'Documento de Identidad del Cliente';

COMMENT ON COLUMN  "Cliente"."FK_CEDULA_REPRESENTANTE" IS 'Documento de Identidad de su representante actual';

COMMENT ON COLUMN  "Cliente"."PRIMER_NOMBRE" IS 'Primer Nombre del cliente';

COMMENT ON COLUMN  "Cliente"."SEGUNDO_NOMBRE" IS 'Segundo nombre del cliente';

COMMENT ON COLUMN  "Cliente"."PRIMER_APELLIDO" IS 'Primer apellido del cliente';

COMMENT ON COLUMN  "Cliente"."SEGUNDO_APELLIDO" IS 'Segundo apellido del cliente';

COMMENT ON COLUMN  "Cliente"."CORREO_ELECTRONICO" IS 'Correo electrónico del cliente';

COMMENT ON COLUMN  "Cliente"."GENERO" IS 'Genero del cliente (Masculino o Femenino)';

COMMENT ON COLUMN  "Cliente"."FECHA_NACIMIENTO" IS 'Fecha de nacimiento del cliente';

COMMENT ON COLUMN  "Cliente"."TEL_CONTACTO" IS 'Teléfono de contacto del cliente';

COMMENT ON COLUMN  "Cliente"."ESTADO" IS 'Estado de actividad del cliente dentro del sistema (A: Activo, I: Inactivo)';

COMMENT ON TABLE  "Inventario" IS 'Tabla de Rompimiento entre las tablas Producto y Región (Cuales productos hay en una región)'
;


COMMENT ON COLUMN  "Inventario"."FK_ID_REGION" IS 'Identificador de la región a la cual pertenece el producto';

COMMENT ON COLUMN  "Inventario"."FK_ID_PRODUCTO" IS 'Identificador del producto perteneciente a la región';

COMMENT ON COLUMN  "Inventario"."PRECIO" IS 'Precio del producto';

COMMENT ON TABLE  "Pedido" IS 'Tabla que almacena los datos de los Pedidos'
;


COMMENT ON COLUMN  "Pedido"."ID_PEDIDO" IS 'Identificador del pedido';

COMMENT ON COLUMN  "Pedido"."FK_CEDULA_REPRESENTANTE" IS 'Documento de identidad del representante que realizó el pedido';

COMMENT ON COLUMN  "Pedido"."FK_CEDULA_CLIENTE" IS 'Documento de identidad del cliente que ordenó el pedido';

COMMENT ON COLUMN  "Pedido"."MONTO" IS 'Precio total del pedido (Calculado por la Base de Datos)';

COMMENT ON COLUMN  "Pedido"."CALIFICACION_REP" IS 'Calificación de 0 a 5 proporcionada por el cliente dependiendo de la calidad del servicio ootorgada por el representante';

COMMENT ON COLUMN  "Pedido"."TIPO_PAGO" IS 'Tipo de pago seleccionado por el cliente (P: PSE, C: Tarjeta de crédito)';

COMMENT ON COLUMN  "Pedido"."ESTADO" IS 'Estado del pago del pedido (PP: Por Pagar (Por defecto), C: Cancelado)';

COMMENT ON COLUMN  "Pedido"."FECHA_PEDIDO" IS 'Fecha donde el pedido fue cancelado por el cliente';

CREATE SEQUENCE "SEQ_Pedido_ID_PEDIDO" 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;


CREATE OR REPLACE TRIGGER "TRG_Pedido_ID_PEDIDO" 
	BEFORE INSERT 
	ON "Pedido" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_Pedido_ID_PEDIDO".NEXTVAL 
		INTO :NEW."ID_PEDIDO" 
		FROM DUAL; 
	END;

/


COMMENT ON TABLE  "PedidoProducto" IS 'Tabla de Rompimiento entre las tablas Pedido y Producto (Cuantos productos hay en un pedido)'
;


COMMENT ON COLUMN  "PedidoProducto"."FK_ID_PEDIDO" IS 'Identificador del pedido realizado por el representante y ordenado por el cliente';

COMMENT ON COLUMN  "PedidoProducto"."FK_ID_PRODUCTO" IS 'Identificador de un producto que haya sido ordenado en el pedido';

COMMENT ON TABLE  "Periodo" IS 'Tabla que almacena los datos de los Periodos'
;


COMMENT ON COLUMN  "Periodo"."ID_PERIODO" IS 'Identificador del periodo de campaña';

COMMENT ON COLUMN  "Periodo"."FECHA_INICIO" IS 'Fecha inicial del periodo';

COMMENT ON COLUMN  "Periodo"."FECHA_FIN" IS 'Fecha final del pedido';

COMMENT ON TABLE  "Producto" IS 'Tabla que almacena los datos de los Productos'
;


COMMENT ON COLUMN  "Producto"."ID_PRODUCTO" IS 'Identificador del producto';

COMMENT ON COLUMN  "Producto"."FK_ID_CATEGORIA" IS 'Identificador de la categoría a la que pertenece el producto';

COMMENT ON COLUMN  "Producto"."NOMBRE" IS 'Nombre del producto';

COMMENT ON TABLE  "Region" IS 'Tabla que almacena los datos de las Regiones'
;


COMMENT ON COLUMN  "Region"."ID_REGION" IS 'Identificador de la región';

COMMENT ON COLUMN  "Region"."FK_ID_DIRECTOR" IS 'Identificador del representante que ocupa el puesto de director en la región';

COMMENT ON COLUMN  "Region"."NOMBRE" IS 'Nombre de la región';

CREATE SEQUENCE "SEQ_Region_ID_REGION" 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;


CREATE OR REPLACE TRIGGER "TRG_Region_ID_REGION" 
	BEFORE INSERT 
	ON "Region" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_Region_ID_REGION".NEXTVAL 
		INTO :NEW."ID_REGION" 
		FROM DUAL; 
	END;

/


COMMENT ON TABLE  "Representante" IS 'Tabla que almacena los datos de los Representantes'
;


COMMENT ON COLUMN  "Representante"."CEDULA" IS 'Documento de identidad del representante';

COMMENT ON COLUMN  "Representante"."FK_ID_REGION" IS 'Identificador de la región a la cual está afiliada el representante';

COMMENT ON COLUMN  "Representante"."FK_ID_REP_PADRE" IS 'Identificador del representante que lo afilió al sistema';

COMMENT ON COLUMN  "Representante"."PRIMER_NOMBRE" IS 'Primer nombre del representante';

COMMENT ON COLUMN  "Representante"."SEGUNDO_NOMBRE" IS 'Segundo nombre del representante';

COMMENT ON COLUMN  "Representante"."PRIMER_APELLIDO" IS 'Primer apellido del representante';

COMMENT ON COLUMN  "Representante"."SEGUNDO_APELLIDO" IS 'Segundo apellido del representante';

COMMENT ON COLUMN  "Representante"."CORREO_ELECTRONICO" IS 'Correo electrónico del representante';

COMMENT ON COLUMN  "Representante"."GENERO" IS 'Género del representante (Masculino o Femenino)';

COMMENT ON COLUMN  "Representante"."FECHA_NACIMIENTO" IS 'Fecha de nacimiento del representante';

COMMENT ON COLUMN  "Representante"."FECHA_CONTRATO" IS 'Fecha en la que el usuario adquirió los privilegios de representante';

COMMENT ON COLUMN  "Representante"."TEL_CONTACTO" IS 'Teléfono de contacto del representante';

COMMENT ON COLUMN  "Representante"."GRADO" IS 'Grado actual del representante (beginner (Por defecto), junior, senior, master) asignado en el último periodo';

COMMENT ON COLUMN  "Representante"."PROM_CALIFICACION" IS 'Promedio de calificaciones asignadas por sus clientes en cada uno de sus pedidos';

COMMENT ON COLUMN  "Representante"."TOTAL_VENTA" IS 'Monto total de ventas del representante (Calculado por la Base de Datos)';

COMMENT ON COLUMN  "Representante"."ESTADO" IS 'Estado de actividad del representante (A: Activo (Por defecto), I: Inactivo)';

COMMENT ON TABLE  "RepresentantePeriodo" IS 'Tabla de Rompimiento entre las tablas Representante y Pedido (Información de un representante dentro de un periodo en específico)'
;


COMMENT ON COLUMN  "RepresentantePeriodo"."FK_CEDULA_REPRESENTANTE" IS 'Documento de identidad del representante';

COMMENT ON COLUMN  "RepresentantePeriodo"."FK_ID_PERIODO" IS 'Identificador del periodo a calificar';

COMMENT ON COLUMN  "RepresentantePeriodo"."MONTO" IS 'Venta total del representante en el periodo correspondiente';

COMMENT ON COLUMN  "RepresentantePeriodo"."GRADO" IS 'Grado del representante (beginner, junior, senior, master) del periodo correspondiente (Calculado en la aplicación)';

COMMENT ON COLUMN  "RepresentantePeriodo"."PORCENTAJE" IS 'Porcentaje de comision del representante correspondiente a su grado actual';

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "Categoria" 
 ADD CONSTRAINT "PK_Categoria"
	PRIMARY KEY ("ID_CATEGORIA") 
 USING INDEX
;

ALTER TABLE  "Categoria" 
 ADD CONSTRAINT "CK_NOMBRECATEGORIA" CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-z]+$'))
;

CREATE INDEX "IXFK_Categoria_Categoria"   
 ON  "Categoria" ("FK_CATEGORIA_PADRE") 
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "PK_Cliente"
	PRIMARY KEY ("CEDULA") 
 USING INDEX
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "CK_CEDULA_CLIENTE" CHECK (CEDULA>0)
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "CK_NOMBRES_CLIENTE" CHECK (REGEXP_LIKE(PRIMER_NOMBRE,'^[A-Za-z]+$') and (REGEXP_LIKE(SEGUNDO_NOMBRE,'^[A-Za-z]+$') or SEGUNDO_NOMBRE is null)
and REGEXP_LIKE(PRIMER_APELLIDO,'^[A-Za-z]+$') and (REGEXP_LIKE(SEGUNDO_APELLIDO,'^[A-Za-z]+$') or SEGUNDO_NOMBRE is null))
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "CK_CORREO_CLIENTE" CHECK (REGEXP_LIKE(CORREO_ELECTRONICO, '^(\S+)\@(\S+)\.(\S+)$'))
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "CK_GENERO_CLIENTE" CHECK (GENERO in ('M','F'))
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "CK_TELEFONO_CLIENTE" CHECK (TEL_CONTACTO>999999999)
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "CK_ESTADO_CLIENTE" CHECK (ESTADO in ('A','I'))
;

CREATE INDEX "IXFK_Cliente_Representante"   
 ON  "Cliente" ("FK_CEDULA_REPRESENTANTE") 
;

ALTER TABLE  "Inventario" 
 ADD CONSTRAINT "PK_Inventario"
	PRIMARY KEY ("FK_ID_REGION","FK_ID_PRODUCTO") 
 USING INDEX
;

ALTER TABLE  "Inventario" 
 ADD CONSTRAINT "CK_PRECIO" CHECK (PRECIO > 0)
;

CREATE INDEX "IXFK_Inventario_Producto"   
 ON  "Inventario" ("FK_ID_PRODUCTO") 
;

CREATE INDEX "IXFK_Inventario_Region"   
 ON  "Inventario" ("FK_ID_REGION") 
;

ALTER TABLE  "Pedido" 
 ADD CONSTRAINT "PK_PEDIDO"
	PRIMARY KEY ("ID_PEDIDO") 
 USING INDEX
;

ALTER TABLE  "Pedido" 
 ADD CONSTRAINT "CK_MONTOPEDIDO" CHECK (MONTO > 0)
;

ALTER TABLE  "Pedido" 
 ADD CONSTRAINT "CK_CALIFICACIONPEDIDO" CHECK ((CALIFICACION_REP >= 0) AND (CALIFICACION_REP <= 5))
;

ALTER TABLE  "Pedido" 
 ADD CONSTRAINT "CK_TIPOPAGOPEDIDO" CHECK (TIPO_PAGO IN ('P','C','N'))
;

ALTER TABLE  "Pedido" 
 ADD CONSTRAINT "CK_ESTADOPEDIDO" CHECK (ESTADO IN ('PP', 'P'))
;

CREATE INDEX "IXFK_Pedido_Cliente"   
 ON  "Pedido" ("FK_CEDULA_CLIENTE") 
;

CREATE INDEX "IXFK_Pedido_Representante"   
 ON  "Pedido" ("FK_CEDULA_REPRESENTANTE") 
;

ALTER TABLE  "PedidoProducto" 
 ADD CONSTRAINT "PK_PedidoProducto"
	PRIMARY KEY ("FK_ID_PEDIDO","FK_ID_PRODUCTO") 
 USING INDEX
;

CREATE INDEX "IXFK_PedidoProducto_Pedido"   
 ON  "PedidoProducto" ("FK_ID_PEDIDO") 
;

CREATE INDEX "IXFK_PedidoProducto_Producto"   
 ON  "PedidoProducto" ("FK_ID_PRODUCTO") 
;

ALTER TABLE  "Periodo" 
 ADD CONSTRAINT "PK_Periodo"
	PRIMARY KEY ("ID_PERIODO") 
 USING INDEX
;

ALTER TABLE  "Producto" 
 ADD CONSTRAINT "PK_PRODUCTO"
	PRIMARY KEY ("ID_PRODUCTO") 
 USING INDEX
;

ALTER TABLE  "Producto" 
 ADD CONSTRAINT "CK_NOMBREPRODUCTO" CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-z]+$'))
;

CREATE INDEX "IXFK_Producto_Categoria"   
 ON  "Producto" ("FK_ID_CATEGORIA") 
;

ALTER TABLE  "Region" 
 ADD CONSTRAINT "PK_Region"
	PRIMARY KEY ("ID_REGION") 
 USING INDEX
;

ALTER TABLE  "Region" 
 ADD CONSTRAINT "CK_NOMBREREGION" CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-z]+$'))
;

CREATE INDEX "IXFK_Region_Representante"   
 ON  "Region" ("FK_ID_DIRECTOR") 
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "PK_REPRESENTANTE"
	PRIMARY KEY ("CEDULA") 
 USING INDEX
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "CK_NOMBRES_REPRESENTANTE" CHECK (REGEXP_LIKE(PRIMER_NOMBRE,'^[A-Za-z]+$') and (REGEXP_LIKE(SEGUNDO_NOMBRE,'^[A-Za-z]+$') or SEGUNDO_NOMBRE is null)
and REGEXP_LIKE(PRIMER_APELLIDO,'^[A-Za-z]+$') and (REGEXP_LIKE(SEGUNDO_APELLIDO,'^[A-Za-z]+$') or SEGUNDO_NOMBRE is null))
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "CK_CEDULA_REPRESENTANTE" CHECK (CEDULA>0)
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "CK_CORREO_REPRESENTANTE" CHECK (REGEXP_LIKE(CORREO_ELECTRONICO, '^(\S+)\@(\S+)\.(\S+)$'))
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "CK_TELEFONO_REPRESENTANTE" CHECK (TEL_CONTACTO>999999999)
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "CK_GENERO_REPRESENTANTE" CHECK (GENERO in ('M','F'))
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "CK_GRADO_REPRESENTANTE" CHECK (GRADO in ('beginner', 'junior', 'senior', 'master'))
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "CK_ESTADO_REPRESENTANTE" CHECK (ESTADO in ('A', 'I'))
;

CREATE INDEX "IXFK_Representante_Region"   
 ON  "Representante" ("FK_ID_REGION") 
;

CREATE INDEX "IXFK_REPRESENTANTE_REPRESENTANTE"   
 ON  "Representante" ("FK_ID_REP_PADRE") 
;

ALTER TABLE  "RepresentantePeriodo" 
 ADD CONSTRAINT "PK_REPRESENTANTEPERIODO"
	PRIMARY KEY ("FK_CEDULA_REPRESENTANTE","FK_ID_PERIODO") 
 USING INDEX
;

ALTER TABLE  "RepresentantePeriodo" 
 ADD CONSTRAINT "CK_REPRESENTANTEPERIODO" CHECK (MONTO > 0)
;

ALTER TABLE  "RepresentantePeriodo" 
 ADD CONSTRAINT "CK_GRADO" CHECK (GRADO IN ('begginer','junior','senior','master'))
;

ALTER TABLE  "RepresentantePeriodo" 
 ADD CONSTRAINT "CK_PORCENTAJE" CHECK (PORCENTAJE > 0)
;

CREATE INDEX "IXFK_REPRESENTANTEPEDIDO_REPRESENTANTE"   
 ON  "RepresentantePeriodo" ("FK_ID_PERIODO") 
;

CREATE INDEX "IXFK_REPRESENTANTEPERIODO_REPRESENTANTE"   
 ON  "RepresentantePeriodo" ("FK_CEDULA_REPRESENTANTE") 
;

/* Create Foreign Key Constraints */

ALTER TABLE  "Categoria" 
 ADD CONSTRAINT "FK_Categoria_Categoria"
	FOREIGN KEY ("FK_CATEGORIA_PADRE") REFERENCES  "Categoria" ("ID_CATEGORIA")
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "FK_Cliente_Representante"
	FOREIGN KEY ("FK_CEDULA_REPRESENTANTE") REFERENCES  "Representante" ("CEDULA")
;

ALTER TABLE  "Inventario" 
 ADD CONSTRAINT "FK_Inventario_Producto"
	FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES  "Producto" ("ID_PRODUCTO")
;

ALTER TABLE  "Inventario" 
 ADD CONSTRAINT "FK_Inventario_Region"
	FOREIGN KEY ("FK_ID_REGION") REFERENCES  "Region" ("ID_REGION")
;

ALTER TABLE  "Pedido" 
 ADD CONSTRAINT "FK_Pedido_Cliente"
	FOREIGN KEY ("FK_CEDULA_CLIENTE") REFERENCES  "Cliente" ("CEDULA")
;

ALTER TABLE  "Pedido" 
 ADD CONSTRAINT "FK_Pedido_Representante"
	FOREIGN KEY ("FK_CEDULA_REPRESENTANTE") REFERENCES  "Representante" ("CEDULA")
;

ALTER TABLE  "PedidoProducto" 
 ADD CONSTRAINT "FK_PedidoProducto_Pedido"
	FOREIGN KEY ("FK_ID_PEDIDO") REFERENCES  "Pedido" ("ID_PEDIDO")
;

ALTER TABLE  "PedidoProducto" 
 ADD CONSTRAINT "FK_PedidoProducto_Producto"
	FOREIGN KEY ("FK_ID_PRODUCTO") REFERENCES  "Producto" ("ID_PRODUCTO")
;

ALTER TABLE  "Producto" 
 ADD CONSTRAINT "FK_Producto_Categoria"
	FOREIGN KEY ("FK_ID_CATEGORIA") REFERENCES  "Categoria" ("ID_CATEGORIA")
;

ALTER TABLE  "Region" 
 ADD CONSTRAINT "FK_Region_Representante"
	FOREIGN KEY ("FK_ID_DIRECTOR") REFERENCES  "Representante" ("CEDULA")
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "FK_Representante_Region"
	FOREIGN KEY ("FK_ID_REGION") REFERENCES  "Region" ("ID_REGION")
;

ALTER TABLE  "Representante" 
 ADD CONSTRAINT "FK_Representante_Representante"
	FOREIGN KEY ("FK_ID_REP_PADRE") REFERENCES  "Representante" ("CEDULA")
;

ALTER TABLE  "RepresentantePeriodo" 
 ADD CONSTRAINT "FK_RepresentantePedido_Representante"
	FOREIGN KEY ("FK_CEDULA_REPRESENTANTE") REFERENCES  "Representante" ("CEDULA")
;

ALTER TABLE  "RepresentantePeriodo" 
 ADD CONSTRAINT "FK_RepresentantePeriodo_Periodo"
	FOREIGN KEY ("FK_ID_PERIODO") REFERENCES  "Periodo" ("ID_PERIODO")
;
