CREATE OR REPLACE SYNONYM REP_CLIENTE
FOR PK_NATAME."RepresentanteCliente";

CREATE OR REPLACE SYNONYM INV
FOR PK_NATAME."Inventario";

CREATE OR REPLACE SYNONYM PED_PROD
FOR PK_NATAME."PedidoProducto";

CREATE OR REPLACE SYNONYM REP_PER
FOR PK_NATAME."RepresentantePeriodo";